name: Fine-tune Model

on:
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install InstructLab
        run: |
          python -m pip install --upgrade pip
          pip install -U instructlab

      - name: Create InstructLab config manually
        run: |
          mkdir -p ~/.instructlab
          cat <<EOF > ~/.instructlab/config.yaml
          taxonomy_repo_path: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/taxonomy
          model_repo_path: /home/runner/.local/share/instructlab/models
          EOF

      - name: Train the model
        run: |
          ilab train --config config.yaml



