name: Fine-tune Model

on:
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install InstructLab
        run: |
          pip install -U instructlab

      - name: Initialize InstructLab config
        run: |
          ilab config init

      - name: Train the model
        run: |
          ilab train --config config.yaml

